### ISSUE TITLE
Unable to add manga

### ISSUE THREAD

**Issue by axeII** [sendyhalim/Yomu#9] opened 2017-05-31 11:55 UTC
Unable to click on the option "Add manga+". 
What happens is that left tab disappear. I was expecting input file window.  
Version 1.5.0
OS X: 10.12.4

**Comment by sendyhalim** [comment] 2017-05-31 13:22
@L3rchal Hi, thanks for the report!
Hmm weird, I can't reproduce the error on my machine. I tried with: 
- Empty manga collection and click on it 
- Non-empty manga collection and click on it

So I think I would need you to post a screenshot of it and can you please try with older versions? https://github.com/sendyhalim/Yomu/releases

**Comment by axeII** [comment] 2017-05-31 14:09
![addman](https://cloud.githubusercontent.com/assets/13370338/26635929/82d3f64a-461b-11e7-84d9-346f7c187477.gif)

**Comment by sendyhalim** [comment] 2017-05-31 19:11
@L3rchal Oh I know (it's a "bad UX" issue), you just need to click the "Search Manga" and type a manga title that you want to search. Any suggestion on how to improve the UX?

![kapture 2017-06-01 at 2 17 10](https://cloud.githubusercontent.com/assets/3948217/26649527/824c088e-4670-11e7-848e-ed2d6deb3d5d.gif)

**Comment by sendyhalim** [comment] 2017-06-05 17:19
I'm closing this issue for now, feel free to re-open 🍻

**Closed as completed by sendyhalim** 2017-06-05 17:19 UTC

**Comment by axeII** [comment] 2017-06-13 16:58
I am sorry for long reply. 
For some reason it didn't work at time I opened issue (probably problem on my side - firewall)
App is awesome, what server are you downloading from? 
**EDIT**: oh i see it's *manga eden*

And my ideas for your application. 

- Double page reading - next to each others (I think you can enjoy more reading manga like that)

- Is it possible to input manga (in format cbz/cbr/zip)? I've got lot of manga however it would awesome to input them into some application which would help me to order them.

- Dark mode would be nice

**PS**: love that app icon.

**Comment by sendyhalim** [comment] 2017-06-14 05:21
No worries. Yea I'm requesting from manga eden, I don't want to keep the manga data just to be safe. 

- Double page reading + dark mode sound awesome, I'll get into it this weekend, thanks for the feedback!
- For reading manga from cbz / cbr / zip, I need to do some research first (I never read / use manga in those formats) 

https://icons8.com provided the free icons :beers:
